osx_image: xcode10
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=Resizin
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap --platform iOS --cache-builds
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push
script:
- set -o pipefail && xcodebuild test -scheme Resizin -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint
deploy:
  provider: releases
  api_key:
    secure: cCg4W6avMlSCmqkdy9PbFeFbU+TPm3nWtis33cyUciQzVftU3q5GHj3xuQLsUtXXKF5pYrFdQgZtIYBSkYhjNOrlwTa2Kt9WR9Yj//EL4YST5FRTXYSyYgy5ZS0iOf8hSe2Q8WWaPMNI0xgUC0gIM0KqoJqDsfYT3QRHFNpPRKgPgJZ481Oe7E1nno78Gd71iWN2fjMoeYYUHN1H1dsSsZKDP5eatcgMZxGDVYmPzzIQjOIpZBHkIV+VMZefWWaVbNaHIFwxzjn1pIbD/oh/tMLZy7cQ1oYa8BOpsIMVIX3pCIQ4KTXbh+xGCFfhcKJEF5N1B0THcpQMoKNDyeQq7wqYydOg6HtxTZW2wLaLIWtX8KTJbOuCROq1YIwdYccCj2aaczGFKnc/qdux/Nnv2LZms9woef9Kwyn/2Ipr/H3pPFJW3kXE896qa6g2Mt6HSY/h+z3ZNSb/N0SrcRxtl2qYZsIP4BeKeVR0FtG/flT6vZpjMmKlPJxEKjUWqkMYOG/6Y6n/Pdxd8WLSBG+Zqj6Lux5mVAJUjg/jcCGebodj1ZAHNEPt+Hk/5hhHFBTVWPyLhhxNfFmHVG2upP9W7MrNt8/V6C2dKfe3R7SllZBBW2rIjYoYCIu/9QtEBmvn/oARUVDeV3ymITsAbH15AubJBXLkzJ0Tg7993i6ah6c=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/Resizin-iOS-SDK
    tags: true
