osx_image: xcode10.2
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=Resizin
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap --platform iOS --cache-builds
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push
script:
- set -o pipefail && xcodebuild test -scheme Resizin -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint
deploy:
  provider: releases
  api_key:
    secure: KaCHh3poL2JFmdlKunkEeFYap/UmjcbKQ8Mro5c/5GPDqBFO4hVmsmx5jbFNkYc7AmIPZxUOWi4sGKwSGf+rlCihCCoeNTc6tFYBRD/WH/UJ6vTTnkqmYxaDnXZjz1qpV3O3JP9775Uf8W6Y/rfmq07/TDn2KV+7V8BnldgWRYSwT0Wum5PKuCC1wCP5I4lGzz6aiTZcc3GlmZr3IVOral0zVJMIKpx7LlPCIJ4DFovGHKD9zscaP24nBVIOAyhH/YBCdpA8MQMptarBd1X7lS/O+i9GfkuZTQtWt5oD4VR60rcAEWKxLUL1UdTt4hcnCo/3Kas+BuUlAIyekQmGNPD0eNsAjudSxFS8vxUbBdjUof4GDIOvlqjvwGmpqTq9ZQ1UgaLMK6dVVjj4ScIpHOKDK2HheTgjw2L0ldj0dN0JH4ZcFT1mAJcHIPHVPh3SlXOy0OHA6E7Fu8uOtHOxXrG6aJSrfpZ5wyJbLTErnQYtgvyPKPLLlSNa+6TEIIluyhqZUp8lUA3+BQ/DRJPq848l1HxBv/UUL+3Jh+H3u786KARFAzctM9StcqeOALzK75DFsyCTnTGbmf+aHLVQvIV7s0kpB+kTmFQYbv04OEEFWIb9qy5WB/0ufi/od8I7HGt+0fA20bppCKk59+LRn7MHNTJtZ8cXHvGtuVji5XM=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: AckeeCZ/Resizin-iOS-SDK
    tags: true
